export const labels = {
  en: {
    invoice: 'INVOICE',
    to: 'Bill To',
    from: 'From',
    invNo: 'Invoice Number',
    date: 'Issue Date',
    due: 'Due Date',
    ref: 'Reference',
    desc: 'Description',
    qty: 'Qty',
    unit: 'Unit Price',
    vat: 'VAT',
    amount: 'Amount',
    subtotal: 'Subtotal',
    total: 'Total Due',
    terms: 'Payment Terms',
    bank: 'Bank Details',
    iban: 'IBAN',
    bic: 'BIC/SWIFT',
    notes: 'Notes',
    vatNo: 'VAT Number',
    kvk: 'KvK',
    thankYou: 'Thank you for your business.',
    reverseCharge: 'VAT reverse charged to recipient (Article 196 EU VAT Directive).',
    vatExempt: 'VAT exempt under KOR (Kleine Ondernemersregeling).',
    noVat: 'Services supplied outside the EU — no VAT applicable.',
    lateFee1: 'Late payments are subject to 1% statutory interest per month.',
    lateFee8: 'Late payments are subject to 8% interest per annum (EU Late Payment Directive 2011/7/EU).',
    paymentRef: 'Reference',
  },
  nl: {
    invoice: 'FACTUUR',
    to: 'Gefactureerd aan',
    from: 'Van',
    invNo: 'Factuurnummer',
    date: 'Factuurdatum',
    due: 'Vervaldatum',
    ref: 'Referentie',
    desc: 'Omschrijving',
    qty: 'Aant.',
    unit: 'Stuksprijs',
    vat: 'BTW',
    amount: 'Bedrag',
    subtotal: 'Subtotaal',
    total: 'Totaal te betalen',
    terms: 'Betalingstermijn',
    bank: 'Bankgegevens',
    iban: 'IBAN',
    bic: 'BIC/SWIFT',
    notes: 'Opmerkingen',
    vatNo: 'BTW-nummer',
    kvk: 'KvK-nummer',
    thankYou: 'Dank voor uw vertrouwen.',
    reverseCharge: 'BTW verlegd naar afnemer (artikel 196 EU BTW-richtlijn).',
    vatExempt: 'Vrijgesteld van BTW op grond van de Kleine Ondernemersregeling (KOR).',
    noVat: 'Diensten buiten de EU — geen BTW van toepassing.',
    lateFee1: 'Bij te late betaling wordt de wettelijke rente van 1% per maand in rekening gebracht.',
    lateFee8: 'Bij te late betaling wordt 8% rente per jaar in rekening gebracht (EU-richtlijn betalingsachterstand 2011/7/EU).',
    paymentRef: 'Betalingskenmerk',
  },
} as const

export type Language = 'en' | 'nl'
export type Labels = typeof labels.en
